### ISSUE TITLE
Electrum-stratis-2.7.17 not encripted the data

### ISSUE THREAD

**Issue by alex-ru** [stratisproject/electrum#30]
Electrum-stratis-2.7.17 not encripted the data on all versions  in windows 10. At start opens at once without demanding any password. The reference to the description is given on other wallet. As this works specifically not clearly.

**Comment by dev0tion** [comment]
The private seed is encrypted, this is the same as it was on Electrum for Bitcoin at v2.7.
Changing it is currently not planned, as we will probably move to our own SPV solution.

**Comment by alex-ru** [comment]
Electrum for bitcoins (electrum-3.1.0-portable) when opening offers - This file is encrypted with a password.
Electrum-stratis-2.7.17 at start opens without password at once (and also seed, etc.) your Electrum-stratis-2.7.17 is not protected from unauthorized opening by the stranger.

**Comment by alex-ru** [comment]
when it is ready SPV solution?

**Comment by dev0tion** [comment]
Electrum for Bitcoin 2.7.17 did it the same as we are doing it in our version.
Can't say when the new solution will be ready, but the current version of Electrum is 100% safe to use because the private seed is encrypted. 
There's a lot of data in the file indeed, but if you're worried about privacy then you shouldn't use an SPV solution in the first place, because third parties can get all your wallet data (except for the private seed ofcourse) even if the wallet file is completely encrypted.

**Comment by alex-ru** [comment]
thanks for the answer

**Comment by dev0tion** [comment]
You're welcome!
